<?php
// This file generated by Propel 1.6.1 convert-conf target
// from XML runtime conf file /Users/jon/Development/Personal/P2PT2/database/system/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'p2p' => 
    array (
      'adapter' => 'pgsql',
      'connection' => 
      array (
        'dsn' => 'pgsql:host=localhost dbname=p2p2 user=jon password=',
        'user' => 'jon',
        'password' => '',
      ),
    ),
  ),
  'generator_version' => '1.6.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-database-conf.php');
return $conf;